name: Pipeline CI - Teste Backend 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Instalar dependências via pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com pytest
        working-directory: ./backend
        env:
          APP_ENV: testing
        run: |
          pytest test_api.py
