name: Pipeline CI - Teste Backend 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Instalar dependências via pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Newman
        run: |
         npm install -g newman

      - name: Instalar dependências do projeto Node.js
        run: npm ci

      - name: Iniciar servidor Flask
        run: |
          nohup python backend/app.py &

      - name: Iniciar servidor frontend
        run: |
          nohup python3 -m http.server 5500 --directory frontend &
          
      - name: Rodar testes com pytest
        working-directory: ./backend
        env:
          APP_ENV: testing
        run: |
          pytest test_api.py

      - name: Rodar testes da API com Newman
        run: |
          npm run test:api

      - name: Executar testes E2E com Cypress
        run: npx cypress run